name: space-mission-control

services:

  # ── Étape 1 : Spring Boot ────────────────────────────────────────
  boot:
    build:
      context: space_app
    container_name: space-boot

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://48.220.33.217:3316/smc_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: bu5q+Fx5Cq3bJ0jLHhAZsF5m3IbGuNBm

    ports:
      - 8080:8080

    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/8080' 2>/dev/null"]
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 30s

    networks:
      - space

  # ── Étape 2 : Angular ────────────────────────────────────────────
  angular:
    build:
      context: space_app_Angular
    container_name: space-angular

    ports:
      - 4200:80

    depends_on:
      boot:
        condition: service_healthy

    networks:
      - space

networks:
  space:
    name: space
