spring.application.name=space

# Configuration datasource MySQL (serveur partagé formation)
spring.datasource.url=jdbc:mysql://48.220.33.217:3316/smc_db
spring.datasource.username=root
spring.datasource.password=bu5q+Fx5Cq3bJ0jLHhAZsF5m3IbGuNBm
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Clé secrète JWT (min 32 caractères pour HMAC-SHA256)
jwt.secret=6E5A7234753778214125442A472D4B6150645367556B58703273357638792F42
